2010-03-01 07:54:51-0800 [-] Log opened.
2010-03-01 07:54:51-0800 [-] twistd 9.0.0 (/usr/bin/python 2.6.2) starting up.
2010-03-01 07:54:51-0800 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2010-03-01 07:54:51-0800 [-] twisted.internet.protocol.ServerFactory starting on 8021
2010-03-01 07:54:51-0800 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x9327c2c>
2010-03-01 07:54:51-0800 [-] twisted.internet.protocol.ServerFactory starting on 8020
2010-03-01 07:54:51-0800 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x9327d4c>
2010-03-01 07:56:05-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 07:56:05-0800 [twisted.internet.protocol.ServerFactory] Starting factory <jobtracker.JobClientFactory instance at 0x934328c>
2010-03-01 07:56:05-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 07:56:05-0800 [Uninitialized] Got new client!
2010-03-01 07:56:05-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 664, in doConnect
	    self._connectDone()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 671, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/protocol.py", line 364, in makeConnection
	    self.connectionMade()
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 23, in connectionMade
	    self.factory.clients.append(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 07:56:05-0800 [Uninitialized] Lost a client!
2010-03-01 07:56:05-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/application/app.py", line 348, in runReactorWithLogging
	    reactor.run()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1166, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1178, in mainLoop
	    self.doIteration(t)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 140, in doSelect
	    _logrun(selectable, _drdw, selectable, method, dict)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 156, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, method=="doRead")
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/posixbase.py", line 194, in _disconnectSelectable
	    selectable.connectionLost(failure.Failure(why))
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 677, in connectionLost
	    Connection.connectionLost(self, reason)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 519, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 33, in connectionLost
	    self.factory.clients.remove(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 07:56:05-0800 [TaskTracker,0,127.0.0.1] Lost a client!
2010-03-01 07:58:28-0800 [JobTracker,0,127.0.0.1] received 'Hi'
2010-03-01 07:58:32-0800 [JobTracker,0,127.0.0.1] received ''
2010-03-01 08:01:12-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 08:01:14-0800 [TaskTracker,1,127.0.0.1] received 'Hi'
2010-03-01 08:10:27-0800 [JobTracker,0,127.0.0.1] received ''
2010-03-01 08:20:13-0800 [-] Received SIGTERM, shutting down.
2010-03-01 08:20:13-0800 [-] (Port 8020 Closed)
2010-03-01 08:20:13-0800 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x9327d4c>
2010-03-01 08:20:13-0800 [-] (Port 8021 Closed)
2010-03-01 08:20:13-0800 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x9327c2c>
2010-03-01 08:20:13-0800 [JobTracker,0,127.0.0.1] Lost a client!
2010-03-01 08:20:13-0800 [TaskTracker,1,127.0.0.1] Lost a client!
2010-03-01 08:20:13-0800 [-] Main loop terminated.
2010-03-01 08:20:13-0800 [-] Server Shut Down.
2010-03-01 08:20:40-0800 [-] Log opened.
2010-03-01 08:20:40-0800 [-] twistd 9.0.0 (/usr/bin/python 2.6.2) starting up.
2010-03-01 08:20:40-0800 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2010-03-01 08:20:40-0800 [-] twisted.internet.protocol.ServerFactory starting on 8021
2010-03-01 08:20:40-0800 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x86d5bac>
2010-03-01 08:20:40-0800 [-] twisted.internet.protocol.ServerFactory starting on 8020
2010-03-01 08:20:40-0800 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0x86d5bec>
2010-03-01 08:20:48-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 08:20:58-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 08:21:02-0800 [JobTracker,0,127.0.0.1] received 'Hello'
2010-03-01 08:21:02-0800 [JobTracker,0,127.0.0.1] Starting factory <jobtracker.JobClientFactory instance at 0x86f026c>
2010-03-01 08:21:02-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 08:21:02-0800 [Uninitialized] Got new client!
2010-03-01 08:21:02-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 664, in doConnect
	    self._connectDone()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 671, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/protocol.py", line 364, in makeConnection
	    self.connectionMade()
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 23, in connectionMade
	    self.factory.clients.append(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 08:21:02-0800 [Uninitialized] Lost a client!
2010-03-01 08:21:02-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/application/app.py", line 348, in runReactorWithLogging
	    reactor.run()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1166, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1178, in mainLoop
	    self.doIteration(t)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 140, in doSelect
	    _logrun(selectable, _drdw, selectable, method, dict)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 156, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, method=="doRead")
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/posixbase.py", line 194, in _disconnectSelectable
	    selectable.connectionLost(failure.Failure(why))
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 677, in connectionLost
	    Connection.connectionLost(self, reason)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 519, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 28, in connectionLost
	    self.factory.clients.remove(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 08:21:02-0800 [TaskTracker,1,127.0.0.1] Lost a client!
2010-03-01 08:21:08-0800 [TaskTracker,0,127.0.0.1] received 'no'
2010-03-01 08:21:13-0800 [JobTracker,0,127.0.0.1] received ''
2010-03-01 08:21:13-0800 [JobTracker,0,127.0.0.1] Starting factory <jobtracker.JobClientFactory instance at 0x86fb88c>
2010-03-01 08:21:13-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 08:21:13-0800 [Uninitialized] Got new client!
2010-03-01 08:21:13-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 664, in doConnect
	    self._connectDone()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 671, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/protocol.py", line 364, in makeConnection
	    self.connectionMade()
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 23, in connectionMade
	    self.factory.clients.append(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 08:21:13-0800 [Uninitialized] Lost a client!
2010-03-01 08:21:13-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/application/app.py", line 348, in runReactorWithLogging
	    reactor.run()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1166, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1178, in mainLoop
	    self.doIteration(t)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 140, in doSelect
	    _logrun(selectable, _drdw, selectable, method, dict)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 156, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, method=="doRead")
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/posixbase.py", line 194, in _disconnectSelectable
	    selectable.connectionLost(failure.Failure(why))
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 677, in connectionLost
	    Connection.connectionLost(self, reason)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 519, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 28, in connectionLost
	    self.factory.clients.remove(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 08:21:13-0800 [TaskTracker,2,127.0.0.1] Lost a client!
2010-03-01 08:53:49-0800 [JobTracker,0,127.0.0.1] received ''
2010-03-01 08:53:49-0800 [JobTracker,0,127.0.0.1] Starting factory <jobtracker.JobClientFactory instance at 0x86f0c6c>
2010-03-01 08:53:49-0800 [twisted.internet.protocol.ServerFactory] Got new client!
2010-03-01 08:53:49-0800 [Uninitialized] Got new client!
2010-03-01 08:53:49-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 146, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 664, in doConnect
	    self._connectDone()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 671, in _connectDone
	    self.protocol.makeConnection(self)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/protocol.py", line 364, in makeConnection
	    self.connectionMade()
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 23, in connectionMade
	    self.factory.clients.append(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 08:53:49-0800 [Uninitialized] Lost a client!
2010-03-01 08:53:49-0800 [Uninitialized] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/application/app.py", line 348, in runReactorWithLogging
	    reactor.run()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1166, in run
	    self.mainLoop()
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/base.py", line 1178, in mainLoop
	    self.doIteration(t)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 140, in doSelect
	    _logrun(selectable, _drdw, selectable, method, dict)
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 84, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/log.py", line 69, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 59, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/python/context.py", line 37, in callWithContext
	    return func(*args,**kw)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/selectreactor.py", line 156, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, method=="doRead")
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/posixbase.py", line 194, in _disconnectSelectable
	    selectable.connectionLost(failure.Failure(why))
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 677, in connectionLost
	    Connection.connectionLost(self, reason)
	  File "/usr/local/lib/python2.6/dist-packages/Twisted-9.0.0-py2.6-linux-i686.egg/twisted/internet/tcp.py", line 519, in connectionLost
	    protocol.connectionLost(reason)
	  File "/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/jobtracker.py", line 28, in connectionLost
	    self.factory.clients.remove(self)
	exceptions.AttributeError: JobClientFactory instance has no attribute 'clients'
	
2010-03-01 08:53:49-0800 [TaskTracker,3,127.0.0.1] Lost a client!
2010-03-01 08:54:33-0800 [-] Received SIGTERM, shutting down.
2010-03-01 08:54:33-0800 [-] (Port 8020 Closed)
2010-03-01 08:54:33-0800 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x86d5bec>
2010-03-01 08:54:33-0800 [-] (Port 8021 Closed)
2010-03-01 08:54:33-0800 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0x86d5bac>
2010-03-01 08:54:33-0800 [TaskTracker,0,127.0.0.1] Lost a client!
2010-03-01 08:54:33-0800 [JobTracker,0,127.0.0.1] Lost a client!
2010-03-01 08:54:33-0800 [-] Main loop terminated.
2010-03-01 08:54:33-0800 [-] Failed to unlink PID file
	Traceback (most recent call last):
	Failure: exceptions.OSError: [Errno 2] No such file or directory: '/home/dexity/danse-workspace/AbInitio/espresso/lab/hydra/usecases/caseA/twistd.pid'
	
2010-03-01 08:54:33-0800 [-] Server Shut Down.
2010-03-01 08:54:49-0800 [-] Log opened.
2010-03-01 08:54:49-0800 [-] twistd 9.0.0 (/usr/bin/python 2.6.2) starting up.
2010-03-01 08:54:49-0800 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2010-03-01 08:54:49-0800 [-] twisted.internet.protocol.ServerFactory starting on 8021
2010-03-01 08:54:49-0800 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0xa471bac>
2010-03-01 08:54:49-0800 [-] twisted.internet.protocol.ServerFactory starting on 8020
2010-03-01 08:54:49-0800 [-] Starting factory <twisted.internet.protocol.ServerFactory instance at 0xa471bec>
2010-03-01 08:55:22-0800 [-] Received SIGTERM, shutting down.
2010-03-01 08:55:22-0800 [-] (Port 8020 Closed)
2010-03-01 08:55:22-0800 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0xa471bec>
2010-03-01 08:55:22-0800 [-] (Port 8021 Closed)
2010-03-01 08:55:22-0800 [-] Stopping factory <twisted.internet.protocol.ServerFactory instance at 0xa471bac>
2010-03-01 08:55:22-0800 [-] Main loop terminated.
2010-03-01 08:55:22-0800 [-] Server Shut Down.
